export const formBoxClass = "container flex flex-col justify-evenly px-2 py-2";
export const labelDivClass = "container flex flex-row p-2 justify-between";
export const labelTextClass = "text-xl text-black font-normal";
export const headingTextClass = "text-4xl font-bold text-black";
export const textInputClass = "border-2 border-black bg-white px-3 h-[2em] focus:outline-none";

export const mainContainerClass = "container mx-auto flex flex-col items-center py-10 justify-start bg-white w-[70em] h-[95vh]";

// Form Styles
export const formDivClass = "container flex w-6/6 flex-row px-2";

// Button Styles
const actioButton = "rounded-sm border-2 border-black text-lg ";
export const actionButtonClass = `${actioButton} bg-purple hover:border-gray-light text-gray-light `;
export const altActionButtonClass = `${actioButton} bg-black shadow-sm rounded-sm px-2 py-2 mr-3 hover:border-black                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          `;
export const actioButtonDisabledClass = `${actioButton} cursor-not-allowed bg-gray text-black hover:border-black `;